### ISSUE TITLE
Node disk size

### ISSUE THREAD

**Issue by ArseniiPetrovich** [binance-chain/node-binary#166]
# Issue description
Our fresh node is only 3 GB in size. Is it ok? Can it be considered as a full node?

# Details
At Ethereum there is a dedicated chart (https://etherscan.io/chartsync/chainarchive) that shows the size that should have the fully synced node. While waiting for fix for #128 we decided to drop one of our nodes and resync it so we won't end up with a major downtime. Today when I decided to check the node status I've found out, that the latest block number is up to date with a current blockchain state:
```
"sync_info": {
      "latest_block_hash": "594B8259AC36855159A38FBA0FFE8FC79E2378A402A724D1C98DADE947EA5FC3",
      "latest_app_hash": "FEF5480121DBEE997E735C2A0431638F6404CB16CE7860AC6A88AD0D2F7DAB99",
      "latest_block_height": "51730558",
      "latest_block_time": "2019-11-29T15:50:12.284254166Z",
      "catching_up": true,
      "index_height": "51730558"
    }
```
However, I decided to check a disk size also. It appeared, that the Binance node after 1 day of sync is only 3.2 Gb in size, slowly increasing, while the broken node is 61Gb. The question is if it is okay, and if this 3.2Gb node can be considered as a full node?

# References
Related to #128 #164

**Comment by huangsuyu** [comment]
I think both of your nodes used `state-sync` to catch up with the network. They DOES NOT download historical blocks before state sync height. Please read the doc here: https://docs.binance.org/fullnode.html#state-sync

Your new node is downloading the new blocks, so its disk size is increasing. But I'm afraid your new node has a slow I/O rate, as it's still showing`"catching_up": true,` Another node of yours has been up for longer time, so it takes a bigger space.

Both of them are fullnode because their state is full up to date and they are able to validate incoming transactions.

**Comment by ArseniiPetrovich** [comment]
Thanks!
